-- LaundroSwipe Supabase schema
-- Use the single master script instead: run supabase/master.sql in Supabase SQL Editor.
-- That file includes: colleges, admins, users, students, orders, order_status_history,
-- RLS policies, triggers, and seed data. Column names match the Next.js app.
